# Generated by Django 5.1.2 on 2024-11-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Parameter'),
        ),
    ]
